services:
  - type: web
    runtime: docker
    name: TransportApp
    repo: https://github.com/PATHANAZAMKHAN/Own-Transport-Details-System.git
    branch: OTS_nest_v3
    plan: free
    region: singapore
    dockerCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: false
