services:
  - name: own-transport-details-system
    type: web
    env: node
    plan: free
    region: singapore
    repo: https://github.com/PATHANAZAMKHAN/Own-Transport-Details-System/tree/OTS_nest_v2
    branch: OTS_nest_v2
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: WEB_URL
        value: https://transport-pdf-service.onrender.com
    autoDeploy: false
    staticPublishPath: public
