# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#

name: Deploy to Railway

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24.11.1
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service TransportApp
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
